[dyad-cli]
git-tree-sha1 = "08f1fef9388f4ab5502f93006c6101c7b698d829"

    [[dyad-cli.download]]
    sha256 = "a61c353e0b79f9a0c97c251cfc04083458a1cd353fa3b5619a287032f82a52d5"
    url = "https://github.com/DyadLang/DyadLangArtifacts/releases/download/v0.6.0/dyad-cli.tar.gz"
